package com.revpm.service;

import com.revpm.dao.UserDAO;
import com.revpm.daoimpl.UserDAOImpl;
import com.revpm.model.User;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class UserService {

	private static UserDAO userDAO = new UserDAOImpl();

	private static final Logger logger = LoggerFactory.getLogger(UserService.class);

	public static void setUserDAO(UserDAO dao) {
		userDAO = dao;
	}

	public static User register(String name, String email, String password) {
		

		logger.info("User registration started for email: {}", email);
		User existingUser = userDAO.findByEmail(email);
		if (existingUser != null) {
			logger.warn("Duplicate registration attempt for email: {}", email);
			return null;
		}

		// userId will be generated by SEQUENCE in DB
		User user = new User(0, name, email, password);
		userDAO.save(user);
		logger.info("User registered successfully for email: {}", email);
		return user;

	}

	public static User login(String email, String password) {

		logger.info("Login attempt for email: {}", email);
		User user = userDAO.findByEmail(email);

		if (user == null) {
			logger.info("Login attempt for email: {}", email);
			return null;
		}

		if (user.getMasterPassword().equals(password)) {
			logger.info("User logged in successfully: {}", email);
			return user;
		}

		logger.error("Invalid login attempt – wrong password for email: {}",email);
		return null;
	}

	public static User getUserByEmail(String email) {
		return userDAO.findByEmail(email);
	}

	public static void updateMasterPassword(int userId, String newPass) {
		userDAO.updatePassword(userId, newPass);
	}

	public static void updateProfile(int userId, String name, String email) {
		userDAO.updateProfile(userId, name, email);
	}
}
